<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ft" nsURI="platform:/plugin/ft/model/ft.ecore" nsPrefix="ft">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FootballTournaments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clubs" upperBound="-1"
        eType="#//Club" containment="true" eOpposite="#//Club/region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tournaments" upperBound="-1"
        eType="#//Tournament" containment="true" eOpposite="#//Tournament/region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tournament">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" lowerBound="1"
        eType="#//GenderKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region" eOpposite="#//Region/tournaments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seasons" upperBound="-1"
        eType="#//Season" containment="true" eOpposite="#//Season/tournament"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Club">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" lowerBound="1"
        eType="#//GenderKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region" eOpposite="#//Region/clubs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seasons" upperBound="-1"
        eType="#//Season" eOpposite="#//Season/clubs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Season">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="startDateMustBeBeforeEndDate clubsGenderMustBeEqualToTournamentGender"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="clubsGenderMustBeEqualToTournamentGender" value="self.clubs.gender->forAll(g | g = self.tournament.gender)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tournament" lowerBound="1"
        eType="#//Tournament" eOpposite="#//Tournament/seasons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clubs" upperBound="-1"
        eType="#//Club" eOpposite="#//Club/seasons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" lowerBound="1"
        upperBound="-1" eType="#//Stage" containment="true" eOpposite="#//Stage/season"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="clubsMustBeInSeason roundNumbersMustBeUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="clubsMustBeInSeason" value="self.season.clubs->includesAll(self.clubs)"/>
      <details key="roundNumbersMustBeUnique" value="self.rounds->isUnique(r | r.roundNumber)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="season" lowerBound="1"
        eType="#//Season" eOpposite="#//Season/stages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clubs" upperBound="-1"
        eType="#//Club"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rounds" upperBound="-1"
        eType="#//Round" containment="true" eOpposite="#//Round/stage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleRoundRobin" eSuperTypes="#//Stage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="numberOfRoundsIsCorrect roundNumbersMustBeInValidRange everyClubMustMeetEveryOtherClubHomeAndAway numberOfMatchesInEachRoundIsCorrect"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="numberOfRoundsIsCorrect" value="self.rounds->size() = (self.clubs->size() - 1) * 2"/>
      <details key="roundNumbersMustBeInValidRange" value="self.rounds.roundNumber->forAll(roundNumber | roundNumber >= 1 and roundNumber &lt;=  ((self.clubs->size() - 1) * 2))"/>
      <details key="everyClubMustMeetEveryOtherClubHomeAndAway" value="self.clubs->collect(club1 | self.clubs->select(club2 | club1 &lt;> club2)->collect(club2  | self.rounds->collect(round | round.matches)->exists(match | match.homeClub = club1 and match.awayClub = club2)))->forAll(v | v)"/>
      <details key="numberOfMatchesInEachRoundIsCorrect" value="self.rounds->forAll(round | round.matches->size() = (self.clubs->size() /2))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="#//Table"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="numberOfStatisticsMustEqualNumberOfClubsInStage"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="numberOfStatisticsMustEqualNumberOfClubsInStage" value="self.statistics->size() = self.stage.clubs->size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statistics" upperBound="-1"
        eType="#//Statistic" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" lowerBound="1" eType="#//DoubleRoundRobin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statistic">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="clubMustBeInStage clubMustBeInOnlyOneStatisticPerTable"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="clubMustBeInStage" value="self.eContainer().stage.clubs->includes(self.club)"/>
      <details key="clubMustBeInOnlyOneStatisticPerTable" value="self.eContainer().statistics.club->count(self.club) = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="club" lowerBound="1" eType="#//Club"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="played" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="won" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="drawn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalsFor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalsAgainst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalDifference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="form" upperBound="6" eType="#//ResultKind"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Round">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roundNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true" eOpposite="#//Match/round"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" lowerBound="1" eType="#//Stage"
        eOpposite="#//Stage/rounds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="homeClubAndAwayClubCannotBeTheSame homeClubMustBeInStage awayClubMustBeInStage homeClubMustBeInOnlyOneMatchPerRound awayClubMustBeInOnlyOneMatchPerRound dateMustBeWithinSeasonStartAndEnd"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="homeClubAndAwayClubCannotBeTheSame" value="self.homeClub &lt;> self.awayClub"/>
      <details key="homeClubMustBeInStage" value="self.round.stage.clubs->includes(self.homeClub)"/>
      <details key="awayClubMustBeInStage" value="self.round.stage.clubs->includes(self.awayClub)"/>
      <details key="homeClubMustBeInOnlyOneMatchPerRound" value="self.round.matches.homeClub->count(self.homeClub) = 1 and self.round.matches.awayClub->count(self.homeClub) = 0"/>
      <details key="awayClubMustBeInOnlyOneMatchPerRound" value="self.round.matches.homeClub->count(self.awayClub) = 0 and self.round.matches.awayClub->count(self.awayClub) = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="round" lowerBound="1" eType="#//Round"
        eOpposite="#//Round/matches"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="homeClub" lowerBound="1"
        eType="#//Club"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="awayClub" lowerBound="1"
        eType="#//Club"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//Result"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeGoalsFullTime" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="awayGoalsFullTime" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winner" eType="#//WinnerKind"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResultKind">
    <eLiterals name="DRAW"/>
    <eLiterals name="WIN" value="1"/>
    <eLiterals name="LOSS" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WinnerKind">
    <eLiterals name="DRAW"/>
    <eLiterals name="HOME" value="1"/>
    <eLiterals name="AWAY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GenderKind">
    <eLiterals name="MEN"/>
    <eLiterals name="WOMEN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ELocalDate" instanceClassName="java.time.LocalDate"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ELocalDateTime" instanceClassName="java.time.LocalDateTime"/>
</ecore:EPackage>
